name: Run file backups for Moodle

on:
  schedule:
    - cron: '33 07 * * *'
jobs:
  fileBackup:
    name: Trigger file backups
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      APP: moodle
      DB_BACKUP_APP: db-backup
      NAMESPACE: 950003-dev
    steps:
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      - name: Run file backups
        run: |
          oc project ${NAMESPACE}
          echo "Current namespace is ${NAMESPACE}"
          podNames=$(oc get pods -l deploymentconfig=moodle --field-selector=status.phase=Running -o name)
          echo $podNames
          for name in $podNames; do
            oc rsync $podNames:/vendor/moodle/moodledata/persistent/filedir/warning.txt /tmp/
            #oc rsync $podNames:/vendor/moodle/moodledata/persistent/models /tmp/
            ls -lrt /tmp
          done

          for name in $podNames; do
            oc exec $podNames -- bash -c "
              mkdir -p /tmp/file-backups && \
              tar -zcvf filedir-$(date "+%Y.%m.%d-%H.%M.%S").tar.gz /vendor/moodle/moodledata/persistent/filedir && \
              mv filedir-*.tar.gz /tmp/file-backups && \
              cp /vendor/moodle/moodledata/persistent/filedir/warning.txt /tmp/file-backups
              "
          done